name: modrinth_api
description: A basic wrapper for most of Modrinth's API
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '^3.0.1'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependencies: 
  build_runner: ^2.1.11 
  crypto: ^3.0.2
  http: ^1.0.0
  json_annotation: ^4.5.0 
  json_serializable: ^6.2.0
