name: modrinth_api
description: A basic wrapper for most of Modrinth's API
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '^3.0.1'

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  lints: ^2.0.0
  test: ^1.16.0

dependencies:
  crypto: ^3.0.2
  http: ^1.0.0
  http_parser: ^4.0.2
  json_annotation: ^4.8.1
  path: ^1.8.3
